/* soapdiff_countObject.h
   Generated by gSOAP 2.7.11 from diff_count.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapdiff_countObject_H
#define soapdiff_countObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

class diff_countService : public soap
{    public:
	diff_countService()
	{ static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"WSref", "http://schemas.xmlsoap.org/ws/2002/04/reference/", NULL, NULL},
	{"ns", "urn:diff_count", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces) this->namespaces = namespaces; };
	virtual ~diff_countService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__getCurrentFoundCount(struct soap*, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__changeConditionToFind(struct soap*, int color, int threshold, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__resetCounter(struct soap*, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getAFrameHexBinary(struct soap*, struct xsd__hexBinary *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getAFramebase64Binary(struct soap*, struct xsd__base64Binary *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getAFramebaseDimeStream(struct soap*, struct xsd__Dimebase64Binary *result);

#endif
