#include "inc.h"

char *SystemCallNameTable[] =
{
    "sys_restart_syscall", //000
    "eixt",                //001
    "fork",                //002
    "read",                //003
    "write",               //004
    "open",                //005
    "close",               //006
    "waitpid",             //007
    "creat",               //008
    "link",                //009
    "unlink",              //010
    "execve",              //011
    "chdir",               //012
    "time",                //013
    "mknod",               //014
    "chmod",               //015
    "lchown16",            //016
    "break",               //017
    "stat",                //018
    "lseek",               //019
    "getpid",              //020
    "mount",               //021
    "old_umount",          //022
    "setuid16",            //023
    "getuid16",            //024
    "stime",               //025
    "ptrace",              //026
    "alarm",               //027
    "fstat",               //028
    "pause",               //029
    "utime",               //030
    "stty",                //031
    "gtty",                //032
    "access",              //033
    "nice",                //034
    "ftime",               //035
    "sync",                //036
    "kill",                //037
    "rename",              //038
    "mkdir",               //039
    "rmdir",               //040
    "dup",                 //041
    "pipe",                //042
    "times",               //043
    "prof",                //044
    "brk",                 //045
    "setgid16",            //046
    "getgid16",            //047
    "signal",              //048
    "geteuid16",           //049
    "getegid16",           //050
    "acct",                //051
    "umount",              //052
    "lock",                //053
    "ioctl",               //054
    "fcntl",               //055
    "mpx",                 //056
    "setpgid",             //057
    "ulimit",              //058
    "olduname",            //059
    "umask",               //060
    "chroot",              //061
    "ustat",               //062
    "dup2",                //063
    "getppid",             //064
    "getpgrp",             //065
    "setsid",              //066
    "sigaction",           //067
    "sgetmask",            //068
    "ssetmask",            //069
    "setreuid16",          //070
    "setregid16",          //071
    "sigsuspend",          //072
    "sigpending",          //073
    "sethostname",         //074
    "setrlimit",           //075
    "old_getrlimit",       //076
    "getrusage",           //077
    "gettimeofday",        //078
    "settimeofday",        //079
    "getgroups16",         //080
    "setgroups16",         //081
    "oldSelect",           //082
    "symlink",             //083
    "lstat",               //084
    "readlink",            //085
    "uselib",              //086
    "swapon",              //087
    "reboot",              //088
    "old_readdir",         //089
    "old_mmap",            //090
    "munmap",              //091
    "truncate",            //092
    "ftruncate",           //093
    "fchmod",              //094
    "fchown16",            //095
    "getpriority",         //096
    "setpriority",         //097
    "profil",              //098
    "statfs",              //099
    "fstatfs",             //100
    "ioperm",              //101
    "socketcall",          //102
    "syslog",              //103
    "setitimer",           //104
    "getitimer",           //105
    "newstat",             //106
    "newlstat",            //107
    "newfstat",            //108
    "uname",               //109
    "iopl",                //110
    "vhangup",             //111
    "idle",                //112
    "vm86old",             //113
    "wait4",               //114
    "swapoff",             //115
    "sysinfo",             //116
    "ipc",                 //117
    "fsync",               //118
    "sigreturn",           //119
    "clone",               //120
    "setdomainname",       //121
    "newuname",            //122
    "modifyLdt",           //123
    "adjtimex",            //124
    "mprotect",            //125
    "sigprocmask",         //126
    "createModule",        //127
    "initModule",          //128
    "deleteModule",        //129
    "getKernelSyms",       //130
    "quotactl",            //131
    "getpgid",             //132
    "fchdir",              //133
    "bdflush",             //134
    "sysfs",               //135
    "personality",         //136
    "afsSyscall",          //137
    "setfsuid16",          //138
    "setfsgid16",          //139
    "llseek",              //140
    "getdents",            //141
    "select",              //142
    "flock",               //143
    "msync",               //144
    "readv",               //145
    "writev",              //146
    "getsid",              //147
    "fdatasync",           //148
    "sysctl",              //149
    "mlock",               //150
    "munlock",             //151
    "mlockall",            //152
    "munlockall",          //153
    "schedSetparam",       //154
    "schedGetparam",       //155
    "schedSetscheduler",   //156
    "schedGetscheduler",   //157
    "schedYield",          //158
    "schedGetPriorityMax", //159
    "schedGetPriorityMin", //160
    "schedRrGetInterval",  //161
    "nanosleep",           //162
    "mremap",              //163
    "setresuid16",         //164
    "getresuid16",         //165
    "vm86",                //166
    "queryModule",         //167
    "poll",                //168
    "nfsservctl",          //169
    "setresgid16",         //170
    "getresgid16",         //171
    "prctl",               //172
    "rt_sigreturn",        //173
    "rt_sigaction",        //174
    "rt_sigprocmask",      //175
    "rt_sigpending",       //176
    "rt_sigtimedwait",     //177
    "rt_sigqueueinfo",     //178
    "rt_sigsuspend",       //179
    "pread64",             //180
    "pwrite64",            //181
    "chown16",             //182
    "getcwd",              //183
    "capget",              //184
    "capset",              //185
    "sigaltstack",         //186
    "sendfile",            //187
    "getpmsg",             //188
    "putpmsg",             //189
    "vfork",               //190
    "getrlimit",           //191
    "mmap2",               //192
    "truncate64",          //193
    "ftruncate64",         //194
    "stat64",              //195
    "lstat64",             //196
    "fstat64",             //197
    "lchown",              //198
    "getuid",              //199
    "getgid",              //200
    "geteuid",             //201
    "getegid",             //202
    "setreuid",            //203
    "setregid",            //204
    "getgroups",           //205
    "setgroups",           //206
    "fchown",              //207
    "setresuid",           //208
    "getresuid",           //209
    "setresgid",           //210
    "getresgid",           //211
    "chown",               //212
    "setuid",              //213
    "setgid",              //214
    "setfsuid",            //215
    "setfsgid",            //216
    "spivot_root",         //217
    "mincore",             //218
    "madvise",             //219
    "getdents64",          //220
    "fcntl64",             //221
    "sys_ni_syscall",      //222
    "sys_ni_syscall",      //223
    "gettid",              //224
    "readahead",           //225
    "setxattr",            //226
    "lsetxattr",           //227
    "fsetxattr",           //228
    "getxattr",            //229
    "lgetxattr",           //230
    "fgetxattr",           //231
    "listxattr",           //232
    "llistxattr",          //233
    "llistxattr",          //234
    "removexattr",         //235
    "lremovexattr",        //236
    "fremovexattr",        //237
    "tkill",               //238
    "sendfile64",          //239
    "futex",               //240
    "schedSetaffinity",    //241
    "schedGetaffinity",    //242
    "setThreadArea",       //243
    "gGetThreadArea",      //244
    "ioSetup",             //245
    "ioDestroy",           //246
    "ioGetevents",         //247
    "ioSubmit",            //248
    "ioCancel",            //249
    "fadvise64",           //250
    "sys_ni_syscall",      //251
    "exit_group",          //252
    "lookup_dcookie",      //253
    "epoll_create",        //254
    "epoll_ctl",           //255
    "epoll_wait",          //256
    "remap_file_pages",    //257
    "set_tid_address",     //258
    "timer_create",        //259
    "timer_settime",       //260
    "timer_gettime",       //261
    "timer_getoverrun",    //262
    "timer_delete",        //263
    "clock_settime",       //264
    "clock_gettime",       //265
    "clock_getres",        //266
    "clock_nanosleep",     //267
    "statfs64",            //268
    "fstatfs64",           //269
    "tgkill",              //270
    "utimes",              //271
    "fadvise64_64",        //272
    "vserver",             //273
    "mbind",               //274
    "get_mempolicy",       //275
    "set_mempolicy",       //276
    "mq_open",             //277
    "mq_unlink",           //278
    "mq_timedsend",        //279
    "mq_timedreceive",     //280
    "mq_notify",           //281
    "nq_getsetattr",       //282
    "kexec_load",          //283
    "waitid",              //284
    "sys_setaltroot",      //285
    "add_key"              //286
    "request_key",         //287
    "keyctl",              //288
    "ioprio_set",          //289
    "ioprio_get",          //290
    "inotify_init",        //291
    "inotify_add_watch",   //292
    "inotify_rm_watch",    //293
    "migrate_pages",       //294
    "openat",              //295
    "mkdirat",             //296
    "mknodat",             //297
    "fchownat",            //298
    "futimesat",           //299
    "fstatat64",           //300
    "unlinkat",            //301
    "renameat",            //302
    "linkat",              //303
    "symlinkat",           //304
    "readlinkat",          //305
    "fchmodat",            //306
    "faccessat",           //307
    "pselect6",            //308
    "ppoll",               //309
    "unshare",             //310
    "set_robust_list",     //311
    "get_robust_list",     //312
    "splice",              //313
    "sync_file_range",     //314
    "tee",                 //315
    "vmsplice",            //316
    "move_pages"           //327
};
